############################################              DOCKER COMPOSE            ###########################################   
#
# VERSION 1.0 (apache-superset)
# AUTHOR: OUAGUENI Kousseila <ouaguenikousseila@gmail.com>
# DESCRIPTION: apache superset docker-compose.yml
# Modified/revamped version of the https://github.com/apache/superset/docker-compose.yml

version: '3'
services:
  redis:
    image: redis:3.2
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
  superset:
    image: kousseila/superset-mysql:${SUPERSET_VERSION}
    restart: always
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASS: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      SUPERSET_ENV: ${SUPERSET_ENV}
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
    ports:
      - 5555:5555
      - 8088:8088
    depends_on:
      - mysql
      - redis
    volumes:
      - ../config/:/home/superset/config/
#    networks:
 #     - apache-superset-network
  mysqlworkbench:
    image: lscr.io/linuxserver/mysql-workbench:latest
    container_name: mysql-workbench
  #  environment:
    #  - PUID=1000
    #  - PGID=1000
   #   - TZ=Europe/London
   # volumes:
   #   - /path/to/config:/config
    ports:
      - 3000:3000
   # cap_add:
     # - IPC_LOCK
    restart: unless-stopped
 #   depends_on:
   #   - mysql
volumes:
  mysql:
    external: false
  redis:
    external: false
  #mysqlworkbench: 
  #  external: false
    
  
 #   - PUID=1000
 #   - PGID=1000
   # - TZ= Europe/London
   # Volumes:
   # mysqldata
   # ports:
   # - 3000:3000
#    cap_add:
   # - IPC_LOCK
  # restart : unless-stopped
   
    
    

    
#networks:
  #   apache-superset-network:
 #     driver: bridge

